apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "mychart.fullname" . }}
  labels:
    {{- include "mychart.labels" . | indent 4 }}
spec:
  selector:
    matchLabels:
      {{- include "mychart.labels" . | indent 6 }}
  replicas: {{ .Values.server.replicaCount }}
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        {{- include "mychart.labels" . | indent 8 }}
        env: {{ .Values.env }}
        {{- if .Values.podLabels }}
        {{- toYaml .Values.podLabels | nindent 8 }}
        {{- end }}
      annotations:
        {{- if .Values.podAnnotations }}
        {{- toYaml .Values.podAnnotations | nindent 8 }}
        {{- end }}
        {{- if .Values.additionalAnnotations }}
        {{- toYaml .Values.additionalAnnotations | nindent 8 }}
        {{- end }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: {{ template "mychart.fullname" . }}
          image: "{{ .Values.image.name }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          command: ["/bin/sh"]
          args:
          {{- range .Values.extraArgs }}
          - {{ . }}
          {{- end }}
          resources:
            {{- with .Values.resources }}
            {{- . | toYaml | nindent 12 }}
            {{- end }}
          readinessProbe:
            httpGet:
              path: /health
              # 使用ports定义的名字
              port: {{ .Values.service.targetPort }}
            timeoutSeconds: 60
            failureThreshold: 1
            periodSeconds: 3
          env:
          {{- range $k, $v := .Values.server.env }}
          - name: {{ $k }}
            value: {{ $v | quote }}
          {{- end }}
          ports:
          - name: {{ template "mychart.fullname" . }}
            containerPort: {{ .Values.service.targetPort }}
          volumeMounts:
          {{- if .Values.volumes.server.extraVolumeMounts }}
          {{- toYaml .Values.volumes.server.extraVolumeMounts | nindent 10 }}
          {{- end }}
        {{- if eq (default "False" $.Values.sidecar.type) "True" }}
        {{- toYaml .Values.sidecar.containers | nindent 8 }}
        {{- end }} 
      volumes:
      {{- if .Values.volumes.server.extraVolumes }}
      {{- toYaml .Values.volumes.server.extraVolumes | nindent 6 }}
      {{- end }}
      restartPolicy: Always
