apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: {{ include "mychart.fullname" . }}-hpa
spec:
  minReplicas: {{ .Values.hpa.minReplicaCount }}
  maxReplicas: {{ .Values.hpa.maxReplicaCount }}
  metrics:
  - resource:
      name: memory
      target:
        averageUtilization: {{ .Values.hpa.memory.averageUtilization }}
        type: Utilization
    type: Resource
  - resource:
      name: cpu
      target:
        averageUtilization: {{ .Values.hpa.cpu.averageUtilization }}
        type: Utilization
    type: Resource
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ include "mychart.fullname" . }}